from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass

EMMA_SIGNALS = [
    {
        "id": 11115,
        "name": "Forward active energy",
        "unit": "kWh",
        "custom_name": "Forward Active Energy",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 11116,
        "name": "Reverse active energy",
        "unit": "kWh",
        "custom_name": "Reverse Active Energy",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    {
        "id": 11208,
        "name": "Reactive power",
        "unit": "kvar",
        "custom_name": "Reactive Power",
        "device_class": SensorDeviceClass.REACTIVE_POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11207,
        "name": "Active power",
        "unit": "kW",
        "custom_name": "Active Power",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10014,
        "name": "Power factor",
        "custom_name": "Power Factor",
        "unit": None,
        "device_class": SensorDeviceClass.POWER_FACTOR,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11209,
        "name": "Active power Pa",
        "unit": "kW",
        "custom_name": "Active Power Pa",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11210,
        "name": "Active power Pb",
        "unit": "kW",
        "custom_name": "Active Power Pb",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11211,
        "name": "Active power Pc",
        "unit": "kW",
        "custom_name": "Active Power Pc",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11204,
        "name": "Phase A voltage",
        "unit": "V",
        "custom_name": "Phase A Voltage",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11205,
        "name": "Phase B voltage",
        "unit": "V",
        "custom_name": "Phase B Voltage",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 11206,
        "name": "Phase C voltage",
        "unit": "V",
        "custom_name": "Phase C Voltage",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10009,
        "name": "Phase A current",
        "unit": "A",
        "custom_name": "Phase A Current",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10010,
        "name": "Phase B current",
        "unit": "A",
        "custom_name": "Phase B Current",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    {
        "id": 10011,
        "name": "Phase C current",
        "unit": "A",
        "custom_name": "Phase C Current",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
]

# Configuration signals from deviceExt/get-config-signals (cached, not realtime).
EMMA_CONFIG_SIGNALS = [
    {
        "id": 230700177,
        "name": "Peak Shaving",
        "unit": None,
        "custom_name": "Peak Shaving",
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
        "source": "config",
        "enum_options": [
            "No control",
            "Active power limit",
            "Apparent power limit",
        ],
    },
    {
        "id": 230700178,
        "name": "Backup power SOC for peak shaving",
        "unit": "%",
        "custom_name": "Backup Power SOC for Peak Shaving",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "source": "config",
    },
    {
        "id": 230700179,
        "name": "Peak power schedule",
        "unit": "kW",
        "custom_name": "Peak Power",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "source": "config",
        "peak_schedule": True,
    },
    {
        "id": 21110,
        "name": "Allowed AC charge power",
        "unit": "kW",
        "custom_name": "Allowed AC Charge Power",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "source": "config",
    },
    {
        "id": 21021,
        "name": "Working mode",
        "unit": None,
        "custom_name": "Working Mode",
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
        "source": "config",
        "enum_options": [
            "Maximum self-consumption",
            "Fully fed to grid",
            "TOU",
            "Third-party dispatch",
        ],
    },
    {
        "id": 230700278,
        "name": "Charge from AC",
        "unit": None,
        "custom_name": "Charge from AC",
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
        "source": "config",
        "enum_options": ["Disable", "Enable"],
    },
    {
        "id": 230700279,
        "name": "Grid charge cutoff SOC",
        "unit": "%",
        "custom_name": "Grid Charge Cutoff SOC",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
        "source": "config",
    },
    {
        "id": 21115,
        "name": "Active power control mode",
        "unit": None,
        "custom_name": "Active Power Control Mode",
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
        "source": "config",
        "enum_options": [
            "Unlimited",
            "Zero Export Limitation",
            "Limited Power Grid(kW)",
            "Limited Power Grid(%)",
        ],
    },
    {
        "id": 21098,
        "name": "Max. grid feed-in power",
        "unit": "kW",
        "custom_name": "Max Grid Feed-in Power",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "source": "config",
    },
    {
        "id": 230700200,
        "name": "Maximum Mains Power",
        "unit": "kW",
        "custom_name": "Maximum Mains Power",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
        "source": "config",
    },
    {
        "id": 230700180,
        "name": "PV Power Priority",
        "unit": None,
        "custom_name": "PV Power Priority",
        "device_class": SensorDeviceClass.ENUM,
        "state_class": None,
        "source": "config",
        "enum_options": ["Battery first", "Appliances first"],
    },
]
